### ISSUE TITLE
Should bidirectional Edges be returned on `Node.EdgesTo()`?

### ISSUE THREAD

**Issue by refl3ction** [emicklei/dot#28]
### Description
Hello!
Given the following code, I was expecting the function call `b.EdgesTo(a)` to return an edge since the direction of the edge is bidirectional, resulting in something like this: `A <-> B`, but the function returns an empty list. Can you enlighten me?

```go
        g := dot.NewGraph(dot.Directed)
	a := g.Node("A").Attr("shape", "record")
	b := g.Node("B").Attr("shape", "record")
	c := g.Node("C").Attr("shape", "record")

	a.Edge(b).Attr("dir", "both")
	a.Edge(c)

	ATOB := a.EdgesTo(b)
	BTOA := b.EdgesTo(a)

	for _, edge := range ATOB {
		fmt.Printf("EdgeTo To %s\n", edge.To().ID())
	}
	for _, edge := range BTOA {
		fmt.Printf("EdgeFrom To %s\n", edge.To().ID())
	}
```

Thanks! This library is handy!

**Comment by emicklei** [comment]
thank you for reporting this. 

Looks like you are expecting the library to call `b.Edge(a)` by setting the "dir" attribute to "both.
If you add that call in you program, the result may not be what you want:

<img width="185" alt="image" src="https://user-images.githubusercontent.com/686220/202419252-4c1a0203-24b5-4437-b8f7-c32723afa02b.png">

I think you want to make that call *without* showing the extra visible edge because of the "dir" attribute.

Interesting problem to solve.

**Comment by emicklei** [comment]
how about
```
	edges := g.Bidirectional(a,b)
	// first edge will have style=invis
	// last edge will have dir=both
``

**Comment by emicklei** [comment]
```
func Bidirectional(a, b dot.Node) []dot.Edge {
	e1 := a.Edge(b).Attr("style", "invis")
	e2 := b.Edge(a).Attr("dir", "both")
	return []dot.Edge{e1, e2}
}
```
<img width="178" alt="image" src="https://user-images.githubusercontent.com/686220/202425547-d4389f25-0bce-4e10-8601-89a68212b0c7.png">

**Comment by emicklei** [comment]
or
```
edges := a.BidirectionalEdge(b)
```
